sudo: required
services:
  - docker

before_install:
  - docker build -t hazemsamak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hazemsamak/react-test npm run test

after_success:
  - docker build -t hazemsamak/multi-client ./client
  - docker build -t hazemsamak/multi-nginx ./nginx
  - docker build -t hazemsamak/multi-server ./server
  - docker build -t hazemsamak/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push hazemsamak/multi-client
  - docker push hazemsamak/multi-nginx
  - docker push hazemsamak/multi-server
  - docker push hazemsamak/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-867748103188"
  on:
    branch: master
